version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../tmp/db/pg/db/postgresql/data:/var/lib/postgresql/data
      - ../tmp/db/pg/db/dumps:/var/lib/dumps
  web:
    image: youpressed/juice-core-server:0.0.1
    command: bash -c "rm -f tmp/pids/* && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ..:/app/juice-core
    ports:
      - "3000:3000"
    depends_on:
      - db
